import type { Lead } from "./types";

/**
 * Datos semilla del pipeline (14 leads, bandas 4 caliente / 7 tibio / 3 frío).
 * Se reemplazan por los datos reales de R2 (/api/consola/leads) en H17.
 * Los totales del score SIEMPRE igualan la suma de sus 4 dimensiones:
 * el número lo calcula código determinista, no el LLM.
 */
export const mockLeads: Lead[] = [
  {
    id: "lead_001",
    tipo: "B2C",
    estado_identificacion: "identificado",
    etapa_embudo: "listo_para_asesor",
    identidad: {
      nombre: "María Villacís",
      email: "maria.villacis@correo.ec",
      documento: "0912345678",
      documento_valido: true,
    },
    necesidad: "Quiere empezar a invertir sus ahorros pero no sabe por dónde",
    objeciones: ["Le preocupa perder dinero"],
    senales: { perfil_riesgo: "moderado", monto_declarado_usd: 10000, horizonte: "1 a 3 meses" },
    score: {
      interes: 25,
      presupuesto: 20,
      perfil: 25,
      urgencia: 18,
      total: 88,
      banda: "caliente",
      justificacion:
        "Interés alto: pidió hablar con un asesor y completó el quiz de perfil. Presupuesto: declaró USD 10,000. Perfil: sin experiencia previa, encaja con el Programa Inicial. Urgencia: horizonte de 1 a 3 meses.",
    },
    ruta_sugerida: "asesoria_inversion",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-11T22:54:00-05:00" },
      comunicaciones_comerciales: { otorgado: true, timestamp: "2026-07-11T22:54:00-05:00" },
    },
    ultima_actividad: "2026-07-11T22:58:00-05:00",
    accion_propuesta: {
      id: "acc_001",
      lead_id: "lead_001",
      tipo: "agendar_reunion",
      destinatario: { email: "maria.villacis@correo.ec", nombre: "María Villacís" },
      borrador: {
        canal: "email",
        asunto: "Tu ruta de inversión — agendemos 15 minutos",
        cuerpo:
          "Hola María,\n\nCompletaste el quiz y tu perfil salió moderado. Para resolver tu principal duda —el miedo a perder dinero— te propongo una sesión corta de 15 minutos con un asesor certificado, sin ningún compromiso.\n\n¿Te va bien esta semana?\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Score 88 (caliente). Perfil moderado, sin experiencia. Objeción: miedo a perder dinero → conviene reunión con asesor, no más material.",
      fuentes_consultadas: ["FA-003 §2", "FA-009 §1"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    id: "lead_002",
    tipo: "B2C",
    estado_identificacion: "identificado",
    etapa_embudo: "listo_para_asesor",
    identidad: { nombre: "Diego Espinoza", email: "diego.espinoza@mail.ec", documento: "0923456781", documento_valido: true },
    necesidad: "Tiene un fondo de cesantía y quiere ponerlo a trabajar este trimestre",
    objeciones: ["Tuvo una mala experiencia con una cooperativa"],
    senales: { perfil_riesgo: "agresivo", monto_declarado_usd: 25000, horizonte: "menos de 1 mes" },
    score: {
      interes: 20,
      presupuesto: 20,
      perfil: 20,
      urgencia: 15,
      total: 75,
      banda: "caliente",
      justificacion:
        "Interés alto: preguntó dos veces por horarios de asesoría. Presupuesto: USD 25,000 declarados. Perfil agresivo con experiencia parcial. Urgencia: quiere decidir este mes.",
    },
    ruta_sugerida: "asesoria_inversion",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-12T08:35:00-05:00" },
      comunicaciones_comerciales: { otorgado: true, timestamp: "2026-07-12T08:35:00-05:00" },
    },
    ultima_actividad: "2026-07-12T08:40:00-05:00",
    accion_propuesta: {
      id: "acc_002",
      lead_id: "lead_002",
      tipo: "agendar_reunion",
      destinatario: { email: "diego.espinoza@mail.ec", nombre: "Diego Espinoza" },
      borrador: {
        canal: "email",
        asunto: "Agenda con un asesor — decisión este mes",
        cuerpo:
          "Hola Diego,\n\nVi que quieres mover tu fondo este trimestre. Antes de cualquier decisión, un asesor puede revisar contigo alternativas alineadas a tu perfil y a tu mala experiencia previa.\n\n¿Agendamos mañana?\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Score 75 (caliente). Urgencia declarada de decisión en el mes y monto alto → priorizar reunión antes que material.",
      fuentes_consultadas: ["FA-003 §1", "FA-011 §3"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    // ★ SOFÍA — el caso BLOQUEADO por consentimiento. El plano estrella del vídeo.
    id: "lead_003",
    tipo: "B2C",
    estado_identificacion: "identificado",
    etapa_embudo: "nutricion",
    identidad: { nombre: "Sofía Andrade", email: "sofia@correo.ec" },
    necesidad: "Quiere entender los fondos indexados antes de mover su ahorro programado",
    objeciones: ["No quiere que la llamen ni le escriban vendedores"],
    senales: { perfil_riesgo: "conservador", monto_declarado_usd: 6000, horizonte: "1 a 5 años" },
    score: {
      interes: 22,
      presupuesto: 15,
      perfil: 20,
      urgencia: 15,
      total: 72,
      banda: "caliente",
      justificacion:
        "Interés alto: completó el quiz y descargó dos guías. Presupuesto medio: USD 6,000. Perfil conservador bien definido. Urgencia moderada: decide en semanas, no días.",
    },
    ruta_sugerida: "programa_inicial",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-11T17:10:00-05:00" },
      comunicaciones_comerciales: { otorgado: false },
    },
    ultima_actividad: "2026-07-11T17:15:00-05:00",
    accion_propuesta: {
      id: "acc_003",
      lead_id: "lead_003",
      tipo: "enviar_material",
      destinatario: { email: "sofia@correo.ec", nombre: "Sofía Andrade" },
      borrador: {
        canal: "email",
        asunto: "Guía: fondos indexados para perfil conservador",
        cuerpo:
          "Hola Sofía,\n\nTe comparto la guía de fondos indexados para perfil conservador que complementa el quiz que completaste.\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Score 72 (caliente) pero SIN consentimiento comercial: no puede salir ninguna comunicación. Alternativas: canal telefónico consentido, material educativo ya autorizado o pedir consentimiento en el chat.",
      fuentes_consultadas: ["FA-005 §4"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    id: "lead_004",
    tipo: "B2C",
    estado_identificacion: "identificado",
    etapa_embudo: "calificacion",
    identidad: { nombre: "Valentina Ruiz", email: "valen.ruiz@gmail.com" },
    necesidad: "Acaba de recibir utilidades y quiere invertirlas en vez de gastarlas",
    objeciones: ["Cree que invertir es solo para expertos"],
    senales: { perfil_riesgo: "moderado", monto_declarado_usd: 3500, horizonte: "1 a 3 meses" },
    score: {
      interes: 23,
      presupuesto: 13,
      perfil: 20,
      urgencia: 15,
      total: 71,
      banda: "caliente",
      justificacion:
        "Interés alto: sesión de 20 minutos con 14 preguntas al tutor. Presupuesto bajo-medio: USD 3,500. Perfil moderado tras el quiz. Urgencia: no quiere que el dinero 'se le vaya'.",
    },
    ruta_sugerida: "programa_inicial",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-12T10:02:00-05:00" },
      comunicaciones_comerciales: { otorgado: true, timestamp: "2026-07-12T10:02:00-05:00" },
    },
    ultima_actividad: "2026-07-12T10:05:00-05:00",
    accion_propuesta: {
      id: "acc_004",
      lead_id: "lead_004",
      tipo: "enviar_material",
      destinatario: { email: "valen.ruiz@gmail.com", nombre: "Valentina Ruiz" },
      borrador: {
        canal: "email",
        asunto: "Tu primer paso: Programa Inicial de inversión",
        cuerpo:
          "Hola Valentina,\n\nInvertir no es solo para expertos — el Programa Inicial está diseñado exactamente para tu caso: monto inicial moderado y cero experiencia previa.\n\nTe adjunto la ruta de 3 pasos.\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Score 71 (caliente) pero objeción de autoconfianza → material del Programa Inicial primero; reunión cuando complete el módulo 1.",
      fuentes_consultadas: ["FA-002 §1", "FA-009 §2"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    id: "lead_005",
    tipo: "B2B",
    estado_identificacion: "identificado",
    etapa_embudo: "calificacion",
    identidad: { nombre: "Andrés Cordero", email: "acordero@textilesdelnorte.ec", empresa: "Textiles del Norte" },
    necesidad: "Busca un programa de educación financiera para 40 empleados de planta",
    objeciones: ["Necesita aprobación del directorio para el presupuesto"],
    senales: { perfil_riesgo: "moderado", monto_declarado_usd: 12000 },
    score: {
      interes: 15,
      presupuesto: 20,
      perfil: 15,
      urgencia: 15,
      total: 65,
      banda: "tibio",
      justificacion:
        "Interés medio: pidió propuesta formal pero sin fecha. Presupuesto corporativo: USD 12,000 estimados. Perfil B2B con decisión compartida. Urgencia sujeta a directorio.",
    },
    ruta_sugerida: "ventas_corporativas",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-11T15:20:00-05:00" },
      comunicaciones_comerciales: { otorgado: true, timestamp: "2026-07-11T15:20:00-05:00" },
    },
    ultima_actividad: "2026-07-11T16:02:00-05:00",
    accion_propuesta: {
      id: "acc_005",
      lead_id: "lead_005",
      tipo: "derivar_a_ventas_corporativas",
      destinatario: { email: "acordero@textilesdelnorte.ec", nombre: "Andrés Cordero" },
      borrador: {
        canal: "email",
        asunto: "Propuesta corporativa — Textiles del Norte",
        cuerpo:
          "Estimado Andrés,\n\nGracias por tu interés en capacitar a tu equipo. Derivo tu caso a nuestra área corporativa para preparar la propuesta formal que necesita tu directorio.\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Cuenta B2B con 40 beneficiarios → corresponde al equipo corporativo, no al flujo de personas. La objeción es presupuestaria: adjuntar propuesta formal.",
      fuentes_consultadas: ["FA-021 §1"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    // Caso de propuesta OBSOLETA: los datos cambiaron después del borrador.
    id: "lead_006",
    tipo: "B2B",
    estado_identificacion: "identificado",
    etapa_embudo: "nutricion",
    identidad: { nombre: "Jorge Paredes", email: "jparedes@launion.ec", empresa: "Ferretería La Unión" },
    necesidad: "Explora invertir el excedente de caja de la empresa",
    objeciones: ["Compara con el rendimiento de una póliza bancaria"],
    senales: { perfil_riesgo: "conservador", monto_declarado_usd: 8000 },
    score: {
      interes: 18,
      presupuesto: 15,
      perfil: 15,
      urgencia: 15,
      total: 63,
      banda: "tibio",
      justificacion:
        "Interés medio-alto: tres sesiones en la semana. Presupuesto: USD 8,000 de excedente. Perfil conservador corporativo. Urgencia media: decide al cierre del mes.",
    },
    ruta_sugerida: "ventas_corporativas",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-10T11:30:00-05:00" },
      comunicaciones_comerciales: { otorgado: true, timestamp: "2026-07-10T11:30:00-05:00" },
    },
    ultima_actividad: "2026-07-12T07:45:00-05:00",
    accion_propuesta: {
      id: "acc_006",
      lead_id: "lead_006",
      tipo: "enviar_material",
      destinatario: { email: "jparedes@launion.ec", nombre: "Jorge Paredes" },
      borrador: {
        canal: "email",
        asunto: "Comparativa: excedente de caja vs. póliza",
        cuerpo:
          "Estimado Jorge,\n\nTe comparto la comparativa entre alternativas de inversión del excedente y la póliza tradicional que mencionaste.\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "El lead actualizó su monto declarado después de generar este borrador; la propuesta quedó desactualizada y debe regenerarse.",
      fuentes_consultadas: ["FA-014 §2"],
      estado: "obsoleta",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    id: "lead_007",
    tipo: "B2C",
    estado_identificacion: "identificado",
    etapa_embudo: "nutricion",
    identidad: { nombre: "Carla Ríos", email: "carla.rios@outlook.com" },
    necesidad: "Quiere un fondo para la universidad de su hija (12 años)",
    objeciones: ["Duda entre esto y un seguro educativo"],
    senales: { perfil_riesgo: "conservador", monto_declarado_usd: 5000, horizonte: "más de 5 años" },
    score: {
      interes: 15,
      presupuesto: 13,
      perfil: 15,
      urgencia: 15,
      total: 58,
      banda: "tibio",
      justificacion:
        "Interés medio: hizo el quiz pero no pidió asesor. Presupuesto: USD 5,000 iniciales. Perfil conservador con meta clara. Urgencia baja: horizonte largo.",
    },
    ruta_sugerida: "programa_inicial",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-11T09:12:00-05:00" },
      comunicaciones_comerciales: { otorgado: true, timestamp: "2026-07-11T09:12:00-05:00" },
    },
    ultima_actividad: "2026-07-11T09:30:00-05:00",
    accion_propuesta: {
      id: "acc_007",
      lead_id: "lead_007",
      tipo: "enviar_material",
      destinatario: { email: "carla.rios@outlook.com", nombre: "Carla Ríos" },
      borrador: {
        canal: "email",
        asunto: "Metas a largo plazo: fondo educativo",
        cuerpo:
          "Hola Carla,\n\nPara una meta a 6+ años como la universidad de tu hija, te comparto la guía de inversión por objetivos con ejemplos de horizonte largo.\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Score 58 (tibio) con horizonte largo → nutrir con material específico de metas antes de proponer reunión.",
      fuentes_consultadas: ["FA-007 §3"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    id: "lead_008",
    tipo: "B2C",
    estado_identificacion: "identificado",
    etapa_embudo: "nutricion",
    identidad: { nombre: "Renata Salas", email: "renata.salas@mail.ec" },
    necesidad: "Pregunta cómo funcionan los intereses compuestos para su ahorro mensual",
    objeciones: [],
    senales: { perfil_riesgo: "moderado", monto_declarado_usd: 200, horizonte: "más de 5 años" },
    score: {
      interes: 15,
      presupuesto: 10,
      perfil: 15,
      urgencia: 15,
      total: 55,
      banda: "tibio",
      justificacion:
        "Interés medio: dos sesiones de aprendizaje completadas. Presupuesto: aporte mensual de USD 200. Perfil moderado. Urgencia media: quiere empezar 'pronto'.",
    },
    ruta_sugerida: "programa_inicial",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-10T19:45:00-05:00" },
      comunicaciones_comerciales: { otorgado: true, timestamp: "2026-07-10T19:45:00-05:00" },
    },
    ultima_actividad: "2026-07-11T20:15:00-05:00",
    accion_propuesta: {
      id: "acc_008",
      lead_id: "lead_008",
      tipo: "enviar_material",
      destinatario: { email: "renata.salas@mail.ec", nombre: "Renata Salas" },
      borrador: {
        canal: "email",
        asunto: "Interés compuesto: tu ahorro mensual en el tiempo",
        cuerpo:
          "Hola Renata,\n\nTe comparto el módulo de interés compuesto con la calculadora de aportes mensuales que usamos en clase.\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Score 55 (tibio), aporte periódico pequeño → continuar nutrición con el módulo de interés compuesto.",
      fuentes_consultadas: ["FA-001 §5"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    id: "lead_009",
    tipo: "B2C",
    estado_identificacion: "parcial",
    etapa_embudo: "nutricion",
    identidad: { nombre: "Paula Vera", email: "paula.vera@gmail.com" },
    necesidad: "Recibió una herencia pequeña y no sabe si pagar deudas o invertir",
    objeciones: ["Prioriza liquidez inmediata"],
    senales: { perfil_riesgo: "conservador", monto_declarado_usd: 4000, horizonte: "menos de 1 año" },
    score: {
      interes: 12,
      presupuesto: 12,
      perfil: 13,
      urgencia: 12,
      total: 49,
      banda: "tibio",
      justificacion:
        "Interés medio-bajo: consultas puntuales. Presupuesto: USD 4,000. Perfil conservador con necesidad de liquidez. Urgencia difusa.",
    },
    ruta_sugerida: "programa_inicial",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-09T14:20:00-05:00" },
      comunicaciones_comerciales: { otorgado: true, timestamp: "2026-07-09T14:20:00-05:00" },
    },
    ultima_actividad: "2026-07-10T18:00:00-05:00",
    accion_propuesta: {
      id: "acc_009",
      lead_id: "lead_009",
      tipo: "enviar_material",
      destinatario: { email: "paula.vera@gmail.com", nombre: "Paula Vera" },
      borrador: {
        canal: "email",
        asunto: "¿Pagar deudas o invertir? Guía de decisión",
        cuerpo:
          "Hola Paula,\n\nAntes de invertir conviene ordenar las deudas: te comparto la guía de decisión con el árbol de prioridades financieras.\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Score 49 (tibio). La necesidad real es ordenar finanzas antes de invertir → material de fundamentos, sin presión comercial.",
      fuentes_consultadas: ["FA-006 §1"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    id: "lead_010",
    tipo: "B2C",
    estado_identificacion: "parcial",
    etapa_embudo: "nutricion",
    identidad: { nombre: "Kevin Loor", email: "kevin.loor@hotmail.com" },
    necesidad: "Estudiante: quiere aprender de inversiones desde cero",
    objeciones: ["Sin capital disponible por ahora"],
    senales: { perfil_riesgo: "moderado", monto_declarado_usd: 100 },
    score: {
      interes: 12,
      presupuesto: 10,
      perfil: 12,
      urgencia: 10,
      total: 44,
      banda: "tibio",
      justificacion:
        "Interés medio: completó un módulo educativo. Presupuesto mínimo: USD 100. Perfil en formación. Sin urgencia declarada.",
    },
    ruta_sugerida: "programa_inicial",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-08T21:10:00-05:00" },
      comunicaciones_comerciales: { otorgado: true, timestamp: "2026-07-08T21:10:00-05:00" },
    },
    ultima_actividad: "2026-07-11T21:40:00-05:00",
    accion_propuesta: {
      id: "acc_010",
      lead_id: "lead_010",
      tipo: "enviar_material",
      destinatario: { email: "kevin.loor@hotmail.com", nombre: "Kevin Loor" },
      borrador: {
        canal: "email",
        asunto: "Ruta desde cero: módulo 2 disponible",
        cuerpo:
          "Hola Kevin,\n\n¡Buen avance con el módulo 1! Te habilito el módulo 2 de la ruta desde cero, pensado para empezar con montos pequeños.\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Score 44 (tibio) y sin capital: mantener nutrición educativa; el valor está en el largo plazo del prospecto.",
      fuentes_consultadas: ["FA-002 §2"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    id: "lead_011",
    tipo: "B2C",
    estado_identificacion: "parcial",
    etapa_embudo: "nutricion",
    identidad: { nombre: "Luis Mendoza", email: "luis.mendoza@mail.ec" },
    necesidad: "Comparó plazos fijos y pregunta si 'hay algo mejor'",
    objeciones: ["Desconfía de lo que no sea un banco"],
    senales: { perfil_riesgo: "conservador", monto_declarado_usd: 2000, horizonte: "1 a 5 años" },
    score: {
      interes: 10,
      presupuesto: 8,
      perfil: 13,
      urgencia: 10,
      total: 41,
      banda: "tibio",
      justificacion:
        "Interés bajo-medio: una sola sesión. Presupuesto: USD 2,000. Perfil conservador estricto. Urgencia baja.",
    },
    ruta_sugerida: "programa_inicial",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-07T10:05:00-05:00" },
      comunicaciones_comerciales: { otorgado: true, timestamp: "2026-07-07T10:05:00-05:00" },
    },
    ultima_actividad: "2026-07-09T12:20:00-05:00",
    accion_propuesta: {
      id: "acc_011",
      lead_id: "lead_011",
      tipo: "enviar_material",
      destinatario: { email: "luis.mendoza@mail.ec", nombre: "Luis Mendoza" },
      borrador: {
        canal: "email",
        asunto: "Plazo fijo vs. alternativas reguladas",
        cuerpo:
          "Hola Luis,\n\nTe comparto la comparativa de plazo fijo frente a alternativas reguladas en Ecuador, con riesgos y coberturas de cada una.\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Score 41 (tibio). Desconfianza de base → material comparativo con énfasis regulatorio antes de cualquier contacto.",
      fuentes_consultadas: ["FA-014 §1"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    id: "lead_012",
    tipo: "B2C",
    estado_identificacion: "parcial",
    etapa_embudo: "nutricion",
    identidad: { nombre: "Elena Baus", email: "elena.baus@gmail.com" },
    necesidad: "Curiosidad general: llegó por un video sobre inflación",
    objeciones: [],
    senales: { perfil_riesgo: "moderado" },
    score: {
      interes: 8,
      presupuesto: 8,
      perfil: 8,
      urgencia: 8,
      total: 32,
      banda: "frio",
      justificacion:
        "Interés exploratorio sin señales de compra. Sin monto declarado. Perfil sin quiz. Sin urgencia.",
    },
    ruta_sugerida: "programa_inicial",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-06T16:40:00-05:00" },
      comunicaciones_comerciales: { otorgado: true, timestamp: "2026-07-06T16:40:00-05:00" },
    },
    ultima_actividad: "2026-07-08T09:10:00-05:00",
    accion_propuesta: {
      id: "acc_012",
      lead_id: "lead_012",
      tipo: "enviar_material",
      destinatario: { email: "elena.baus@gmail.com", nombre: "Elena Baus" },
      borrador: {
        canal: "email",
        asunto: "Para empezar: inflación y tu dinero",
        cuerpo:
          "Hola Elena,\n\nGracias por pasar por Futuro Academy. Te comparto la guía introductoria sobre inflación y poder adquisitivo que complementa el video.\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Score 32 (frío): flujo automático de nutrición. Sin señales para intervención humana todavía.",
      fuentes_consultadas: ["FA-001 §1"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    id: "lead_013",
    tipo: "B2C",
    estado_identificacion: "parcial",
    etapa_embudo: "nutricion",
    identidad: { nombre: "Lucía Cedeño", email: "lucia.cedeno@mail.ec" },
    necesidad: "Preguntó qué es un fondo de inversión y se desconectó",
    objeciones: [],
    senales: {},
    score: {
      interes: 7,
      presupuesto: 5,
      perfil: 8,
      urgencia: 7,
      total: 27,
      banda: "frio",
      justificacion:
        "Una consulta única sin seguimiento. Sin monto, sin quiz, sin urgencia. Solo autorizó tratamiento de datos.",
    },
    ruta_sugerida: "programa_inicial",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-05T13:25:00-05:00" },
      comunicaciones_comerciales: { otorgado: false },
    },
    ultima_actividad: "2026-07-05T13:30:00-05:00",
    accion_propuesta: {
      id: "acc_013",
      lead_id: "lead_013",
      tipo: "enviar_material",
      destinatario: { email: "lucia.cedeno@mail.ec", nombre: "Lucía Cedeño" },
      borrador: {
        canal: "email",
        asunto: "Fondos de inversión: la guía corta",
        cuerpo:
          "Hola Lucía,\n\nTe comparto la guía corta de fondos de inversión que responde la pregunta que dejaste en el chat.\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Score 27 (frío) y sin consentimiento comercial → permanece en nutrición automática dentro del chat.",
      fuentes_consultadas: ["FA-004 §1"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
  {
    id: "lead_014",
    tipo: "B2C",
    estado_identificacion: "anonimo",
    etapa_embudo: "nutricion",
    identidad: { nombre: "Marco Tapia", email: "marco.tapia@mail.ec" },
    necesidad: "Solo saludó y preguntó horarios de atención",
    objeciones: [],
    senales: {},
    score: {
      interes: 5,
      presupuesto: 3,
      perfil: 5,
      urgencia: 5,
      total: 18,
      banda: "frio",
      justificacion:
        "Contacto inicial sin señales de necesidad financiera. Pipeline automático hasta que muestre interés.",
    },
    ruta_sugerida: "programa_inicial",
    consentimiento: {
      tratamiento_datos: { otorgado: true, timestamp: "2026-07-04T11:00:00-05:00" },
      comunicaciones_comerciales: { otorgado: true, timestamp: "2026-07-04T11:00:00-05:00" },
    },
    ultima_actividad: "2026-07-04T11:05:00-05:00",
    accion_propuesta: {
      id: "acc_014",
      lead_id: "lead_014",
      tipo: "enviar_material",
      destinatario: { email: "marco.tapia@mail.ec", nombre: "Marco Tapia" },
      borrador: {
        canal: "email",
        asunto: "Bienvenido a Futuro Academy",
        cuerpo:
          "Hola Marco,\n\nGracias por escribirnos. Te dejo el catálogo de rutas de aprendizaje gratuitas para cuando quieras empezar.\n\nSaludos,\nCarlos Peña · Futuro Academy",
      },
      razonamiento:
        "Score 18 (frío): correo de bienvenida del flujo automático de nutrición.",
      fuentes_consultadas: ["FA-001 §1"],
      estado: "pendiente",
      revisado_por: null,
      editado_por_humano: false,
    },
  },
];
