-- Migración Tarea #8: señales, score CV5 y acciones propuestas.
-- Ejecutar una sola vez en PostgreSQL antes de desplegar la versión con CV5.

CREATE TABLE IF NOT EXISTS senales_lead (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id INTEGER NOT NULL UNIQUE,
    presupuesto_declarado DOUBLE PRECISION,
    urgencia_declarada VARCHAR(20),
    num_interacciones INTEGER NOT NULL DEFAULT 0,
    nivel_compromiso VARCHAR(20),
    tiene_presupuesto_aprobado BOOLEAN NOT NULL DEFAULT FALSE,
    tiene_decision_maker BOOLEAN NOT NULL DEFAULT FALSE,
    plazo_decision VARCHAR(50),
    competidores_evaluados JSON,
    notas TEXT,
    actualizado_en TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_senales_lead_lead_id ON senales_lead(lead_id);

CREATE TABLE IF NOT EXISTS scores_lead (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id INTEGER NOT NULL UNIQUE,
    dimension_interes DOUBLE PRECISION NOT NULL DEFAULT 0,
    dimension_capacidad DOUBLE PRECISION NOT NULL DEFAULT 0,
    dimension_urgencia DOUBLE PRECISION NOT NULL DEFAULT 0,
    dimension_fit DOUBLE PRECISION NOT NULL DEFAULT 0,
    total DOUBLE PRECISION NOT NULL DEFAULT 0,
    banda VARCHAR(20) NOT NULL DEFAULT 'frio',
    justificacion TEXT NOT NULL DEFAULT '',
    calculado_en TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_scores_lead_lead_id ON scores_lead(lead_id);

CREATE TABLE IF NOT EXISTS acciones_propuestas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id INTEGER NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    destinatario VARCHAR(200) NOT NULL,
    mensaje_sugerido TEXT NOT NULL,
    snapshot_senales JSON,
    generado_por VARCHAR(200) NOT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'pendiente',
    revisado_por VARCHAR(200),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_acciones_propuestas_lead_id ON acciones_propuestas(lead_id);
