-- Migración completa para sincronizar columnas de los modelos SQLAlchemy
-- definidos en backend/app/models.py con las tablas reales de la base de datos.
-- No incluye campos que solo existan en los schemas Pydantic.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS rol VARCHAR(50) NOT NULL DEFAULT 'ejecutivo';

ALTER TABLE conversations
    ADD COLUMN IF NOT EXISTS token_sesion VARCHAR(512);

ALTER TABLE acciones_propuestas
    ADD COLUMN IF NOT EXISTS asunto VARCHAR(300),
    ADD COLUMN IF NOT EXISTS razonamiento TEXT,
    ADD COLUMN IF NOT EXISTS fuentes_consultadas JSONB,
    ADD COLUMN IF NOT EXISTS snapshot_senales JSONB,
    ADD COLUMN IF NOT EXISTS revisado_por VARCHAR(200),
    ADD COLUMN IF NOT EXISTS revisado_en TIMESTAMP,
    ADD COLUMN IF NOT EXISTS motivo_rechazo TEXT,
    ADD COLUMN IF NOT EXISTS borrador_final JSONB,
    ADD COLUMN IF NOT EXISTS editado_por_humano BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE senales_lead
    ADD COLUMN IF NOT EXISTS objetivo VARCHAR(50),
    ADD COLUMN IF NOT EXISTS horizonte VARCHAR(20),
    ADD COLUMN IF NOT EXISTS pidio_asesor BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS mensajes_intercambiados INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS completo_quiz BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS monto_declarado_usd DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS experiencia_inversion VARCHAR(30),
    ADD COLUMN IF NOT EXISTS perfil_riesgo VARCHAR(50),
    ADD COLUMN IF NOT EXISTS num_colaboradores INTEGER,
    ADD COLUMN IF NOT EXISTS presupuesto_capacitacion_usd DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS es_decisor BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS solicito_propuesta BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS documento_valido BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS ruc_valido BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS email_valido BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS email_corporativo BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS presupuesto_declarado DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS urgencia_declarada VARCHAR(20),
    ADD COLUMN IF NOT EXISTS num_interacciones INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS nivel_compromiso VARCHAR(20),
    ADD COLUMN IF NOT EXISTS tiene_presupuesto_aprobado BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS tiene_decision_maker BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS plazo_decision VARCHAR(50),
    ADD COLUMN IF NOT EXISTS competidores_evaluados JSONB,
    ADD COLUMN IF NOT EXISTS notas TEXT,
    ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMP;

ALTER TABLE scores_lead
    ADD COLUMN IF NOT EXISTS dimension_interes DOUBLE PRECISION DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS dimension_capacidad DOUBLE PRECISION DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS dimension_urgencia DOUBLE PRECISION DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS dimension_fit DOUBLE PRECISION DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS total DOUBLE PRECISION DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS banda VARCHAR(20),
    ADD COLUMN IF NOT EXISTS justificacion TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS calculado_en TIMESTAMP;

ALTER TABLE leads_v2
    ADD COLUMN IF NOT EXISTS nombre VARCHAR(200),
    ADD COLUMN IF NOT EXISTS email VARCHAR(200),
    ADD COLUMN IF NOT EXISTS email_normalizado VARCHAR(200),
    ADD COLUMN IF NOT EXISTS telefono VARCHAR(50),
    ADD COLUMN IF NOT EXISTS cedula VARCHAR(20),
    ADD COLUMN IF NOT EXISTS empresa VARCHAR(200),
    ADD COLUMN IF NOT EXISTS cargo VARCHAR(200),
    ADD COLUMN IF NOT EXISTS estado_identificacion VARCHAR(50) DEFAULT 'anonimo',
    ADD COLUMN IF NOT EXISTS etapa_embudo VARCHAR(50) DEFAULT 'nuevo',
    ADD COLUMN IF NOT EXISTS segmento VARCHAR(10) DEFAULT 'b2c',
    ADD COLUMN IF NOT EXISTS necesidad TEXT,
    ADD COLUMN IF NOT EXISTS objeciones JSONB,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE oportunidades
    ADD COLUMN IF NOT EXISTS nombre VARCHAR(300),
    ADD COLUMN IF NOT EXISTS tipo VARCHAR(50),
    ADD COLUMN IF NOT EXISTS resumen TEXT,
    ADD COLUMN IF NOT EXISTS valor_estimado DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS score_actual DOUBLE PRECISION DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS propietario VARCHAR(200) DEFAULT 'carlos@futuroacademy.ec',
    ADD COLUMN IF NOT EXISTS moneda VARCHAR(10) DEFAULT 'USD',
    ADD COLUMN IF NOT EXISTS probabilidad_cierre DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS ruta_sugerida VARCHAR(50),
    ADD COLUMN IF NOT EXISTS etapa VARCHAR(50) DEFAULT 'nuevo',
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE consentimientos
    ADD COLUMN IF NOT EXISTS tratamiento_datos_otorgado BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS tratamiento_datos_fecha TIMESTAMP,
    ADD COLUMN IF NOT EXISTS tratamiento_datos_canal VARCHAR(50),
    ADD COLUMN IF NOT EXISTS comunicaciones_otorgado BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS comunicaciones_fecha TIMESTAMP,
    ADD COLUMN IF NOT EXISTS comunicaciones_canal VARCHAR(50),
    ADD COLUMN IF NOT EXISTS version_politica VARCHAR(50),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE eventos_auditoria
    ADD COLUMN IF NOT EXISTS actor VARCHAR(20),
    ADD COLUMN IF NOT EXISTS actor_id VARCHAR(200),
    ADD COLUMN IF NOT EXISTS tipo_evento VARCHAR(60),
    ADD COLUMN IF NOT EXISTS lead_id INTEGER,
    ADD COLUMN IF NOT EXISTS payload JSONB,
    ADD COLUMN IF NOT EXISTS timestamp TIMESTAMP;

ALTER TABLE messages
    ADD COLUMN IF NOT EXISTS sender VARCHAR(20),
    ADD COLUMN IF NOT EXISTS content TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS conversation_id INTEGER;

ALTER TABLE leads
    ADD COLUMN IF NOT EXISTS name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS email VARCHAR(150),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(30),
    ADD COLUMN IF NOT EXISTS lead_type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS company VARCHAR(100),
    ADD COLUMN IF NOT EXISTS interest VARCHAR(100),
    ADD COLUMN IF NOT EXISTS budget DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS urgency VARCHAR(50),
    ADD COLUMN IF NOT EXISTS lead_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS status VARCHAR(50),
    ADD COLUMN IF NOT EXISTS user_id INTEGER;

ALTER TABLE documento_corpus
    ADD COLUMN IF NOT EXISTS titulo VARCHAR,
    ADD COLUMN IF NOT EXISTS seccion VARCHAR,
    ADD COLUMN IF NOT EXISTS contenido TEXT,
    ADD COLUMN IF NOT EXISTS publico publico_corpus,
    ADD COLUMN IF NOT EXISTS version VARCHAR,
    ADD COLUMN IF NOT EXISTS aprobado_por VARCHAR,
    ADD COLUMN IF NOT EXISTS cita_visible TEXT;
